FROM docker.io/node:20
COPY . /workspace
WORKDIR /workspace
RUN npm i
RUN npm run build -- --mode production

FROM docker.io/nginx
COPY --from=0 /workspace/dist /usr/share/nginx/html
COPY --from=0 /workspace/default.conf /etc/nginx/conf.d/default.conf
