export const dependencies = {
  alpha: {
    leaders: [66130500853, 66130500828],
    gradient_from: '#67CFF5',
    gradient_to: '#0275E0',
    color_one: '#6987AA',
    color_two: '#42404B',
    color_three: '#8E8D95',
    modal_color: '#9FF0FF',
    tag_one: 'Stealthy',
    tag_two: 'Analytical',
    tag_three: 'Loyal',
    start_with: 'The Cyber Bandits',
    description:
      ', excels in logic and analytical. They are quiet yet caring, using their intellect to solve problems and support their allies in the virtual world.',
  },
  epsilon: {
    leaders: [66130500834, 66130500829],
    gradient_from: '#FC96B2',
    gradient_to: '#FFB982',
    color_one: '#F7789A',
    color_two: '#EC984E',
    color_three: '#7C7BCC',
    modal_color: '#FC96B2',
    tag_one: 'Creative',
    tag_two: 'Energetic',
    tag_three: 'Inspiring',
    start_with: 'The Mystic Creators',
    description:
      ', are known for their creativity and boundless curiosity. They shape the virtual world with innovative ideas and magical prowess, always seeking new frontiers of possibility.',
  },
  eta: {
    leaders: [66130500810, 66130500852],
    gradient_from: '#FFB882',
    gradient_to: '#89AEF4',
    color_one: '#AF373A',
    color_two: '#F0944D',
    color_three: '#43757E',
    modal_color: '#FFB882',
    tag_one: 'Adventurous',
    tag_two: 'Inventive',
    tag_three: 'Brave',
    start_with: 'The Robo Summoners',
    description:
      ', embody bravery and ingenuity. They fearlessly lead the charge in battles, mastering robotics to forge alliances and confront challenges head-on in their virtual adventures.',
  },
  iota: {
    leaders: [66130500843, 66130500826],
    gradient_from: '#43DA94',
    gradient_to: '#E6B3FB',
    color_one: '#B495C7',
    color_two: '#77B178',
    color_three: '#C65089',
    modal_color: '#96F498',
    tag_one: 'Strategic',
    tag_two: 'Intelligent',
    tag_three: 'Confident',
    start_with: 'The Data Diviners',
    description:
      ', possess unmatched intelligence and strategic thinking. They delve into data and mysteries with precision, unraveling secrets and devising meticulous plans to navigate the complexities of their virtual reality.',
  },
};
